linters:
  enable:
    - bodyclose
    - containedctx
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errchkjson
    - errname
    - errorlint
    - exhaustive 
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

run:
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: '(_test\.go|.*test/.+\.go)'
      linters:
        - funlen
    - path: test
      linters:
        - gosec
        - gomnd
